# Generated by Django 4.0.6 on 2022-09-26 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_rename_wishlist_id_wishlist_wishlist_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='variations',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='wishlist',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
