# Generated by Django 4.0.6 on 2022-09-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
