# Generated by Django 4.0.6 on 2022-08-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('discription', models.TextField(blank=True, max_length=200)),
                ('cat_image', models.ImageField(upload_to='photos/categories')),
            ],
        ),
    ]
