# Generated by Django 4.0.6 on 2022-09-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderproduct_status_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
