# Generated by Django 4.0.6 on 2022-10-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_coupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='coupon_min',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='coupon_offer',
            field=models.IntegerField(),
        ),
    ]
